#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

passthru(
    PHP_BINARY.' '.escapeshellarg(__DIR__.'/vendor/bin/testbench')
    .' '.implode(' ', array_map('escapeshellarg', array_slice($argv, 1)))
);